# -*- coding: utf-8 -*-
"""aula_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBrkf5Aw6cwgIm7MM9mtJCfU1ZdvOvLR

Aula 2 - Python
"""

# #isso é uma variável
# #String ou caractere texto

# user = 'Carlos'
# usuario =  'Fernanda'

# # isso é uma variável do tipo inteiro

# number  = 10
# number2 = 23
# number_3= 25

# #isso é uma variável do tipo real(float, ponto flutuante)

# my_number =  2.8
# my_number_2_10 = 3.9

# #isso é uma variável boolena, lógica

# dado = True

# dado2 = False
# dado = 30

# # print(dado)

# a = 2

# #convenção  =

# A = 2
# B = 2.5
# C = 'text'
# D = True
# A = 30

# CONSTANTE = 10
# CONSTANTE = 100

# print(A)




# CPF  = 31321346465
# RG = 1321321321
# ID  = 1132132132


# class = 10

print = 10